### ISSUE TITLE
Support rofi application switcher

### ISSUE THREAD

**Issue by gabyx** [moverest/sway-interactive-screenshot#16]
Would love to see if rofi can be supported if possible ? Would it be easy?

**Comment by moverest** [comment]
I assume it would be pretty straightforward, as only the [`ask()`](https://github.com/moverest/sway-interactive-screenshot/blob/f82b7a92a2559706716326b27dcb2bf3b8f9e3e7/sway-interactive-screenshot#L362) function would need to be re-implemented to use rofi instead of fuzzel.

**Comment by egolep** [comment]
I kinda made this modification, but I made it in the quick and dirty way (aka, I simply replaced `fuzzel` and its args with `rofi`).
If you have a preferred way to handle this selection, I can clean up my solution and make a PR.
