### ISSUE TITLE
Exception when sending notifications with Rofication

### ISSUE THREAD

**Issue by Lukasz-Pe** [moverest/sway-interactive-screenshot#17]
While taking screenshots (image is saved as in config) I get an error as below:
```
sway-interactive-screenshot
Traceback (most recent call last):
  File "/usr/bin/sway-interactive-screenshot", line 838, in <module>
    main()
  File "/usr/bin/sway-interactive-screenshot", line 799, in main
    action_name = notify(
                  ^^^^^^^
  File "/usr/bin/sway-interactive-screenshot", line 414, in notify
    process = subprocess.run(args, capture_output=True, check=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['notify-send', '--icon', PosixPath('/home/lukaszpe/Obrazy/Zrzuty ekranu/Zrzut ekranu_2024-01-29_20:26:42.png'), '-A', 'default=Edit', '-A', 'delete=Delete', '-A', 'dragon=Drag and drop', '-A', 'open=Open', '--', 'Screenshot', 'File saved as <i>~/Obrazy/Zrzuty ekranu/Zrzut ekranu_2024-01-29_20:26:42.png</i>.']' returned non-zero exit status 1.
```
My config file is same (except path and filename to save) with template in Readme.
I am using Arch linux.

**Comment by moverest** [comment]
From your error message `notify-send` is failing for some reason. What's the output if you run the following in a shell?

```bash
notify-send '--icon' '/home/lukaszpe/Obrazy/Zrzuty ekranu/Zrzut ekranu_2024-01-29_20:26:42.png' '-A' 'default=Edit' '-A' 'delete=Delete' '-A' 'dragon=Drag and drop' '-A' '
open=Open' '--' 'Screenshot' 'File saved as <i>~/Obrazy/Zrzuty ekranu/Zrzut ekranu_2024-01-29_20:26:42.png</i>'
```

**Comment by Lukasz-Pe** [comment]
```
notify-send '--icon' '/home/lukaszpe/Obrazy/Zrzuty ekranu/Zrzut ekranu_2024-01-29_20:26:42.png' '-A' 'default=Edit' '-A' 'delete=Delete' '-A' 'dragon=Drag and drop' '-A' '
open=Open' '--' 'Screenshot' 'File saved as <i>~/Obrazy/Zrzuty ekranu/Zrzut ekranu_2024-01-29_20:26:42.png</i>'
Actions are not supported by this notifications server. Displaying non-interactively.
```
I am using rofication from this [repo](https://github.com/DaveDavenport/Rofication) no other notification systems are installed.

**Comment by moverest** [comment]
From the error, it failing because of the actions it seems.

I haven't tried this notification daemon but if you remove `'-A' 'dragon=Drag and drop' '-A' 'open=Open'` from the command it should work. If it does and until support is added for actions in Rofication, you can patch `sway-interactive-screenshot` to not use this feature. This can be done by removing [these lines](https://github.com/moverest/sway-interactive-screenshot/blob/master/sway-interactive-screenshot#L407) in the script:
```python
    for action_name, action_desc in actions or ():
        args.extend(("-A", f"{action_name}={action_desc}"))
```

**Comment by Lukasz-Pe** [comment]
Thanks a lot!
Works as expected.
Maybe an addition of a switch in argparse to torn off interactive mode would be a good idea?

**Comment by moverest** [comment]
This could be put in the configuration but it's an annoying workaround. The user should not have to deal with an implementation detail to make the tool work. Ideally `notify-send` should have a way to silently ignore this and continue if not, it should be able to detect it &mdash; which could be done by looking at the status code and the standard error output.

Now that I think about it, the error says "Actions are not supported by this notifications server. Displaying non-interactively." Did the notification still show up without the patch? If that's the case, we can just ignore the non-zero status code and continue as usual. See if it works with the [`ignore-notify-send-error`](https://github.com/moverest/sway-interactive-screenshot/tree/ignore-notify-send-error) branch. If it does we should be all good.

**Comment by Lukasz-Pe** [comment]
Without the patch I got two notifications as in screenshot.
![obraz_2024-02-03_221109165](https://github.com/moverest/sway-interactive-screenshot/assets/36161245/a246f2d9-8254-4e86-aa04-259466e7cae0)
First position is from [ignore-notify-send-error](https://github.com/moverest/sway-interactive-screenshot/tree/ignore-notify-send-error) branch and the two after that are from unmodified version.
The middle notification is the expected one, last one comes from error.

**Comment by moverest** [comment]
So it looks to be working (I ended up testing it on my machine), I'm going to merge that into master.
