### ISSUE TITLE
Custom save dir

### ISSUE THREAD

**Issue by rif** [moverest/sway-interactive-screenshot#2]
Hey @moverest, 

Thank you for the great helper script!

Could we have an optional env variable that we can set to change the output directory? 

Cheers,
-rif

**Comment by moverest** [comment]
Yes, I'll add a `SWAY_INTERACTIVE_SCREENSHOT_SAVEDIR` which will default to `~`.

**Comment by moverest** [comment]
As of [2.0](https://github.com/moverest/sway-interactive-screenshot/releases/tag/2.0), this is now done with the a configuration file and the `SWAY_INTERACTIVE_SCREENSHOT_SAVEDIR` environment variable will be deprecated and removed at some point in a future release.
