### ISSUE TITLE
Make the screenshot not save automatically

### ISSUE THREAD

**Issue by Turtgun** [moverest/sway-interactive-screenshot#4]
I think the user should decide if they want to save or copy the screenshot because if your clumsy like me, you may make a mistake and then you have to go and delete the screenshot manually. This also will give users the ability to chiose where they want to save the screenshot, instead of it always appearing in the home directory.

**Comment by Turtgun** [comment]
^ Or any other directory that the user decided on.

**Comment by moverest** [comment]
You can chose where to save the screenshots with the `SWAY_INTERACTIVE_SCREENSHOT_SAVEDIR` environment variable. This is how I use it. I have my screenshots saved into a temporary directory that gets wiped when my computer turn off (think `/tmp`). This way I can take multiple screenshots and only select the ones I want to keep or just send it to someone.

But I guess we could have some settings for it to prompt whether the user wants to save or copy the screenshot.
